
package us.co.state.dwr.hbguest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ColoradoWaterHBGuestSoap", targetNamespace = "http://www.dwr.state.co.us/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ColoradoWaterHBGuestSoap {


    /**
     * Retrieve HBGuest County records. The default is a list of Colorado counties.
     * 
     * @param hbStatusHeader
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfCounty
     */
    @WebMethod(operationName = "GetHBGuestCounty", action = "http://www.dwr.state.co.us/GetHBGuestCounty")
    @WebResult(name = "GetHBGuestCountyResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestCounty", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestCounty")
    @ResponseWrapper(localName = "GetHBGuestCountyResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestCountyResponse")
    public ArrayOfCounty getHBGuestCounty(
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest FrostDates records by meas number, start year and end year ( 4 digits : YYYY. The earliest year is 1850 ).
     * 
     * @param hbStatusHeader
     * @param endYear
     * @param measNum
     * @param startYear
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfFrostDates
     */
    @WebMethod(operationName = "GetHBGuestFrostDates", action = "http://www.dwr.state.co.us/GetHBGuestFrostDates")
    @WebResult(name = "GetHBGuestFrostDatesResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestFrostDates", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestFrostDates")
    @ResponseWrapper(localName = "GetHBGuestFrostDatesResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestFrostDatesResponse")
    public ArrayOfFrostDates getHBGuestFrostDates(
        @WebParam(name = "measNum", targetNamespace = "http://www.dwr.state.co.us/")
        int measNum,
        @WebParam(name = "startYear", targetNamespace = "http://www.dwr.state.co.us/")
        short startYear,
        @WebParam(name = "endYear", targetNamespace = "http://www.dwr.state.co.us/")
        short endYear,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsAquiferPicks records by water district (must be between 1 and 80).
     * 
     * @param hbStatusHeader
     * @param wd
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsAquiferPicks
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsAquiferPicksByWD", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsAquiferPicksByWD")
    @WebResult(name = "GetHBGuestGroundWaterWellsAquiferPicksByWDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsAquiferPicksByWD", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsAquiferPicksByWD")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsAquiferPicksByWDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsAquiferPicksByWDResponse")
    public ArrayOfGroundWaterWellsAquiferPicks getHBGuestGroundWaterWellsAquiferPicksByWD(
        @WebParam(name = "wd", targetNamespace = "http://www.dwr.state.co.us/")
        int wd,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsAquiferPicks records by water division (must be between 1 and 7).
     * 
     * @param hbStatusHeader
     * @param div
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsAquiferPicks
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsAquiferPicksByDIV", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsAquiferPicksByDIV")
    @WebResult(name = "GetHBGuestGroundWaterWellsAquiferPicksByDIVResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsAquiferPicksByDIV", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsAquiferPicksByDIV")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsAquiferPicksByDIVResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsAquiferPicksByDIVResponse")
    public ArrayOfGroundWaterWellsAquiferPicks getHBGuestGroundWaterWellsAquiferPicksByDIV(
        @WebParam(name = "div", targetNamespace = "http://www.dwr.state.co.us/")
        int div,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsAquiferPicks records by well number.
     * 
     * @param hbStatusHeader
     * @param wellNumber
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsAquiferPicks
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsAquiferPicksByWellNumber", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsAquiferPicksByWellNumber")
    @WebResult(name = "GetHBGuestGroundWaterWellsAquiferPicksByWellNumberResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsAquiferPicksByWellNumber", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsAquiferPicksByWellNumber")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsAquiferPicksByWellNumberResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsAquiferPicksByWellNumberResponse")
    public ArrayOfGroundWaterWellsAquiferPicks getHBGuestGroundWaterWellsAquiferPicksByWellNumber(
        @WebParam(name = "wellNumber", targetNamespace = "http://www.dwr.state.co.us/")
        int wellNumber,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsDrillersksum records by water district (must be between 1 and 80).
     * 
     * @param hbStatusHeader
     * @param wd
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsDrillersksum
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsDrillersksumByWD", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsDrillersksumByWD")
    @WebResult(name = "GetHBGuestGroundWaterWellsDrillersksumByWDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsDrillersksumByWD", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsDrillersksumByWD")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsDrillersksumByWDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsDrillersksumByWDResponse")
    public ArrayOfGroundWaterWellsDrillersksum getHBGuestGroundWaterWellsDrillersksumByWD(
        @WebParam(name = "wd", targetNamespace = "http://www.dwr.state.co.us/")
        int wd,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsDrillersksum records by water division (must be between 1 and 7).
     * 
     * @param hbStatusHeader
     * @param div
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsDrillersksum
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsDrillersksumByDIV", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsDrillersksumByDIV")
    @WebResult(name = "GetHBGuestGroundWaterWellsDrillersksumByDIVResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsDrillersksumByDIV", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsDrillersksumByDIV")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsDrillersksumByDIVResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsDrillersksumByDIVResponse")
    public ArrayOfGroundWaterWellsDrillersksum getHBGuestGroundWaterWellsDrillersksumByDIV(
        @WebParam(name = "div", targetNamespace = "http://www.dwr.state.co.us/")
        int div,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsDrillersksum records by well number.
     * 
     * @param hbStatusHeader
     * @param wellNumber
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsDrillersksum
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsDrillersksumByWellNumber", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsDrillersksumByWellNumber")
    @WebResult(name = "GetHBGuestGroundWaterWellsDrillersksumByWellNumberResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsDrillersksumByWellNumber", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsDrillersksumByWellNumber")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsDrillersksumByWellNumberResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsDrillersksumByWellNumberResponse")
    public ArrayOfGroundWaterWellsDrillersksum getHBGuestGroundWaterWellsDrillersksumByWellNumber(
        @WebParam(name = "wellNumber", targetNamespace = "http://www.dwr.state.co.us/")
        int wellNumber,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsGeophlogs records by water district (must be between 1 and 80).
     * 
     * @param hbStatusHeader
     * @param wd
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsGeophlogs
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsGeophlogsByWD", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsGeophlogsByWD")
    @WebResult(name = "GetHBGuestGroundWaterWellsGeophlogsByWDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsGeophlogsByWD", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsGeophlogsByWD")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsGeophlogsByWDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsGeophlogsByWDResponse")
    public ArrayOfGroundWaterWellsGeophlogs getHBGuestGroundWaterWellsGeophlogsByWD(
        @WebParam(name = "wd", targetNamespace = "http://www.dwr.state.co.us/")
        int wd,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsGeophlogs records by water division (must be between 1 and 7).
     * 
     * @param hbStatusHeader
     * @param div
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsGeophlogs
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsGeophlogsByDIV", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsGeophlogsByDIV")
    @WebResult(name = "GetHBGuestGroundWaterWellsGeophlogsByDIVResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsGeophlogsByDIV", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsGeophlogsByDIV")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsGeophlogsByDIVResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsGeophlogsByDIVResponse")
    public ArrayOfGroundWaterWellsGeophlogs getHBGuestGroundWaterWellsGeophlogsByDIV(
        @WebParam(name = "div", targetNamespace = "http://www.dwr.state.co.us/")
        int div,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsGeophlogs records by well number.
     * 
     * @param hbStatusHeader
     * @param wellNumber
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsGeophlogs
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsGeophlogsByWellNumber", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsGeophlogsByWellNumber")
    @WebResult(name = "GetHBGuestGroundWaterWellsGeophlogsByWellNumberResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsGeophlogsByWellNumber", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsGeophlogsByWellNumber")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsGeophlogsByWellNumberResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsGeophlogsByWellNumberResponse")
    public ArrayOfGroundWaterWellsGeophlogs getHBGuestGroundWaterWellsGeophlogsByWellNumber(
        @WebParam(name = "wellNumber", targetNamespace = "http://www.dwr.state.co.us/")
        int wellNumber,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsMeasType records by water district (must be between 1 and 80).
     * 
     * @param hbStatusHeader
     * @param wd
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsMeasType
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsMeasTypeByWD", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsMeasTypeByWD")
    @WebResult(name = "GetHBGuestGroundWaterWellsMeasTypeByWDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsMeasTypeByWD", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsMeasTypeByWD")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsMeasTypeByWDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsMeasTypeByWDResponse")
    public ArrayOfGroundWaterWellsMeasType getHBGuestGroundWaterWellsMeasTypeByWD(
        @WebParam(name = "wd", targetNamespace = "http://www.dwr.state.co.us/")
        int wd,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsMeasType records by water division (must be between 1 and 7).
     * 
     * @param hbStatusHeader
     * @param div
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsMeasType
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsMeasTypeByDIV", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsMeasTypeByDIV")
    @WebResult(name = "GetHBGuestGroundWaterWellsMeasTypeByDIVResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsMeasTypeByDIV", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsMeasTypeByDIV")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsMeasTypeByDIVResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsMeasTypeByDIVResponse")
    public ArrayOfGroundWaterWellsMeasType getHBGuestGroundWaterWellsMeasTypeByDIV(
        @WebParam(name = "div", targetNamespace = "http://www.dwr.state.co.us/")
        int div,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsMeasType records by well number.
     * 
     * @param hbStatusHeader
     * @param wellNum
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsMeasType
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsMeasTypeByWellNumber", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsMeasTypeByWellNumber")
    @WebResult(name = "GetHBGuestGroundWaterWellsMeasTypeByWellNumberResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsMeasTypeByWellNumber", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsMeasTypeByWellNumber")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsMeasTypeByWellNumberResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsMeasTypeByWellNumberResponse")
    public ArrayOfGroundWaterWellsMeasType getHBGuestGroundWaterWellsMeasTypeByWellNumber(
        @WebParam(name = "wellNum", targetNamespace = "http://www.dwr.state.co.us/")
        int wellNum,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsPumpingTests records by water district (must be between 1 and 80).
     * 
     * @param hbStatusHeader
     * @param wd
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsPumpingTests
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsPumpingTestsByWD", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsPumpingTestsByWD")
    @WebResult(name = "GetHBGuestGroundWaterWellsPumpingTestsByWDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsPumpingTestsByWD", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsPumpingTestsByWD")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsPumpingTestsByWDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsPumpingTestsByWDResponse")
    public ArrayOfGroundWaterWellsPumpingTests getHBGuestGroundWaterWellsPumpingTestsByWD(
        @WebParam(name = "wd", targetNamespace = "http://www.dwr.state.co.us/")
        int wd,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsPumpingTests records by water division (must be between 1 and 7).
     * 
     * @param hbStatusHeader
     * @param div
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsPumpingTests
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsPumpingTestsByDIV", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsPumpingTestsByDIV")
    @WebResult(name = "GetHBGuestGroundWaterWellsPumpingTestsByDIVResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsPumpingTestsByDIV", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsPumpingTestsByDIV")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsPumpingTestsByDIVResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsPumpingTestsByDIVResponse")
    public ArrayOfGroundWaterWellsPumpingTests getHBGuestGroundWaterWellsPumpingTestsByDIV(
        @WebParam(name = "div", targetNamespace = "http://www.dwr.state.co.us/")
        int div,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsPumpingTests records by well number.
     * 
     * @param hbStatusHeader
     * @param wellNum
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsPumpingTests
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsPumpingTestsByWellNumber", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsPumpingTestsByWellNumber")
    @WebResult(name = "GetHBGuestGroundWaterWellsPumpingTestsByWellNumberResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsPumpingTestsByWellNumber", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsPumpingTestsByWellNumber")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsPumpingTestsByWellNumberResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsPumpingTestsByWellNumberResponse")
    public ArrayOfGroundWaterWellsPumpingTests getHBGuestGroundWaterWellsPumpingTestsByWellNumber(
        @WebParam(name = "wellNum", targetNamespace = "http://www.dwr.state.co.us/")
        int wellNum,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsVolcanics records by water district (must be between 1 and 80).
     * 
     * @param hbStatusHeader
     * @param wd
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsVolcanics
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsVolcanicsByWD", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsVolcanicsByWD")
    @WebResult(name = "GetHBGuestGroundWaterWellsVolcanicsByWDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsVolcanicsByWD", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsVolcanicsByWD")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsVolcanicsByWDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsVolcanicsByWDResponse")
    public ArrayOfGroundWaterWellsVolcanics getHBGuestGroundWaterWellsVolcanicsByWD(
        @WebParam(name = "wd", targetNamespace = "http://www.dwr.state.co.us/")
        int wd,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsVolcanics records by water division (must be between 1 and 7).
     * 
     * @param hbStatusHeader
     * @param div
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsVolcanics
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsVolcanicsByDIV", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsVolcanicsByDIV")
    @WebResult(name = "GetHBGuestGroundWaterWellsVolcanicsByDIVResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsVolcanicsByDIV", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsVolcanicsByDIV")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsVolcanicsByDIVResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsVolcanicsByDIVResponse")
    public ArrayOfGroundWaterWellsVolcanics getHBGuestGroundWaterWellsVolcanicsByDIV(
        @WebParam(name = "div", targetNamespace = "http://www.dwr.state.co.us/")
        int div,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsVolcanics records by well number.
     * 
     * @param hbStatusHeader
     * @param wellNum
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsVolcanics
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsVolcanicsByWellNumber", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsVolcanicsByWellNumber")
    @WebResult(name = "GetHBGuestGroundWaterWellsVolcanicsByWellNumberResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsVolcanicsByWellNumber", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsVolcanicsByWellNumber")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsVolcanicsByWellNumberResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsVolcanicsByWellNumberResponse")
    public ArrayOfGroundWaterWellsVolcanics getHBGuestGroundWaterWellsVolcanicsByWellNumber(
        @WebParam(name = "wellNum", targetNamespace = "http://www.dwr.state.co.us/")
        int wellNum,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest GroundWaterWellsWellMeasTS records by well number, start year and end year(mm/dd/yyyy).
     * 
     * @param hbStatusHeader
     * @param startDate
     * @param wellNum
     * @param endDate
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfGroundWaterWellsWellMeasTS
     */
    @WebMethod(operationName = "GetHBGuestGroundWaterWellsWellMeasTS", action = "http://www.dwr.state.co.us/GetHBGuestGroundWaterWellsWellMeasTS")
    @WebResult(name = "GetHBGuestGroundWaterWellsWellMeasTSResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestGroundWaterWellsWellMeasTS", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsWellMeasTS")
    @ResponseWrapper(localName = "GetHBGuestGroundWaterWellsWellMeasTSResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestGroundWaterWellsWellMeasTSResponse")
    public ArrayOfGroundWaterWellsWellMeasTS getHBGuestGroundWaterWellsWellMeasTS(
        @WebParam(name = "wellNum", targetNamespace = "http://www.dwr.state.co.us/")
        int wellNum,
        @WebParam(name = "startDate", targetNamespace = "http://www.dwr.state.co.us/")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://www.dwr.state.co.us/")
        String endDate,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest NetAmts records by water district (must be between 1 and 80).
     * 
     * @param hbStatusHeader
     * @param wd
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfNetAmts
     */
    @WebMethod(operationName = "GetHBGuestNetAmtsByWD", action = "http://www.dwr.state.co.us/GetHBGuestNetAmtsByWD")
    @WebResult(name = "GetHBGuestNetAmtsByWDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestNetAmtsByWD", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestNetAmtsByWD")
    @ResponseWrapper(localName = "GetHBGuestNetAmtsByWDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestNetAmtsByWDResponse")
    public ArrayOfNetAmts getHBGuestNetAmtsByWD(
        @WebParam(name = "wd", targetNamespace = "http://www.dwr.state.co.us/")
        int wd,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest NetAmts records by water division (must be between 1 and 7).
     * 
     * @param hbStatusHeader
     * @param div
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfNetAmts
     */
    @WebMethod(operationName = "GetHBGuestNetAmtsByDIV", action = "http://www.dwr.state.co.us/GetHBGuestNetAmtsByDIV")
    @WebResult(name = "GetHBGuestNetAmtsByDIVResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestNetAmtsByDIV", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestNetAmtsByDIV")
    @ResponseWrapper(localName = "GetHBGuestNetAmtsByDIVResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestNetAmtsByDIVResponse")
    public ArrayOfNetAmts getHBGuestNetAmtsByDIV(
        @WebParam(name = "div", targetNamespace = "http://www.dwr.state.co.us/")
        int div,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest NetAmts records by WDID.
     * 
     * @param hbStatusHeader
     * @param wdid
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfNetAmts
     */
    @WebMethod(operationName = "GetHBGuestNetAmtsByWDID", action = "http://www.dwr.state.co.us/GetHBGuestNetAmtsByWDID")
    @WebResult(name = "GetHBGuestNetAmtsByWDIDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestNetAmtsByWDID", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestNetAmtsByWDID")
    @ResponseWrapper(localName = "GetHBGuestNetAmtsByWDIDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestNetAmtsByWDIDResponse")
    public ArrayOfNetAmts getHBGuestNetAmtsByWDID(
        @WebParam(name = "wdid", targetNamespace = "http://www.dwr.state.co.us/")
        String wdid,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest ParcelWells records by water district (must be between 1 and 80).
     * 
     * @param hbStatusHeader
     * @param wd
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfParcelWells
     */
    @WebMethod(operationName = "GetHBGuestParcelWellsByWD", action = "http://www.dwr.state.co.us/GetHBGuestParcelWellsByWD")
    @WebResult(name = "GetHBGuestParcelWellsByWDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestParcelWellsByWD", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestParcelWellsByWD")
    @ResponseWrapper(localName = "GetHBGuestParcelWellsByWDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestParcelWellsByWDResponse")
    public ArrayOfParcelWells getHBGuestParcelWellsByWD(
        @WebParam(name = "wd", targetNamespace = "http://www.dwr.state.co.us/")
        int wd,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest ParcelWells records by water division (must be between 1 and 7).
     * 
     * @param hbStatusHeader
     * @param div
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfParcelWells
     */
    @WebMethod(operationName = "GetHBGuestParcelWellsByDIV", action = "http://www.dwr.state.co.us/GetHBGuestParcelWellsByDIV")
    @WebResult(name = "GetHBGuestParcelWellsByDIVResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestParcelWellsByDIV", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestParcelWellsByDIV")
    @ResponseWrapper(localName = "GetHBGuestParcelWellsByDIVResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestParcelWellsByDIVResponse")
    public ArrayOfParcelWells getHBGuestParcelWellsByDIV(
        @WebParam(name = "div", targetNamespace = "http://www.dwr.state.co.us/")
        int div,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest ParcelWells records by WDID.
     * 
     * @param hbStatusHeader
     * @param wdid
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfParcelWells
     */
    @WebMethod(operationName = "GetHBGuestParcelWellsByWDID", action = "http://www.dwr.state.co.us/GetHBGuestParcelWellsByWDID")
    @WebResult(name = "GetHBGuestParcelWellsByWDIDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestParcelWellsByWDID", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestParcelWellsByWDID")
    @ResponseWrapper(localName = "GetHBGuestParcelWellsByWDIDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestParcelWellsByWDIDResponse")
    public ArrayOfParcelWells getHBGuestParcelWellsByWDID(
        @WebParam(name = "wdid", targetNamespace = "http://www.dwr.state.co.us/")
        String wdid,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest SnowCourse records by meas type, start year and end year(mm/dd/yyyy).
     * 
     * @param hbStatusHeader
     * @param startDate
     * @param measNum
     * @param endDate
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfSnowCourse
     */
    @WebMethod(operationName = "GetHBGuestSnowCourse", action = "http://www.dwr.state.co.us/GetHBGuestSnowCourse")
    @WebResult(name = "GetHBGuestSnowCourseResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestSnowCourse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestSnowCourse")
    @ResponseWrapper(localName = "GetHBGuestSnowCourseResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestSnowCourseResponse")
    public ArrayOfSnowCourse getHBGuestSnowCourse(
        @WebParam(name = "measNum", targetNamespace = "http://www.dwr.state.co.us/")
        int measNum,
        @WebParam(name = "startDate", targetNamespace = "http://www.dwr.state.co.us/")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://www.dwr.state.co.us/")
        String endDate,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest station records by water division (must be between 1 and 7).
     * 
     * @param hbStatusHeader
     * @param div
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStation
     */
    @WebMethod(operationName = "GetHBGuestStationByDIV", action = "http://www.dwr.state.co.us/GetHBGuestStationByDIV")
    @WebResult(name = "GetHBGuestStationByDIVResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStationByDIV", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStationByDIV")
    @ResponseWrapper(localName = "GetHBGuestStationByDIVResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStationByDIVResponse")
    public ArrayOfStation getHBGuestStationByDIV(
        @WebParam(name = "div", targetNamespace = "http://www.dwr.state.co.us/")
        int div,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest station records by water district (must be between 1 and 80).
     * 
     * @param hbStatusHeader
     * @param wd
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStation
     */
    @WebMethod(operationName = "GetHBGuestStationByWD", action = "http://www.dwr.state.co.us/GetHBGuestStationByWD")
    @WebResult(name = "GetHBGuestStationByWDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStationByWD", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStationByWD")
    @ResponseWrapper(localName = "GetHBGuestStationByWDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStationByWDResponse")
    public ArrayOfStation getHBGuestStationByWD(
        @WebParam(name = "wd", targetNamespace = "http://www.dwr.state.co.us/")
        int wd,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest available measurement types by a station number.
     * 
     * @param hbStatusHeader
     * @param stationNum
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStationMeasType
     */
    @WebMethod(operationName = "GetHBGuestStationMeasTypeByStationNum", action = "http://www.dwr.state.co.us/GetHBGuestStationMeasTypeByStationNum")
    @WebResult(name = "GetHBGuestStationMeasTypeByStationNumResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStationMeasTypeByStationNum", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStationMeasTypeByStationNum")
    @ResponseWrapper(localName = "GetHBGuestStationMeasTypeByStationNumResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStationMeasTypeByStationNumResponse")
    public ArrayOfStationMeasType getHBGuestStationMeasTypeByStationNum(
        @WebParam(name = "stationNum", targetNamespace = "http://www.dwr.state.co.us/")
        int stationNum,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest StationTS records by meas type, start year and end year (mm/dd/yyyy).
     * 
     * @param hbStatusHeader
     * @param startDate
     * @param measNum
     * @param endDate
     * @param wsDisclaimerHeader
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStationTS
     */
    @WebMethod(operationName = "GetHBGuestStationTS", action = "http://www.dwr.state.co.us/GetHBGuestStationTS")
    @WebResult(name = "GetHBGuestStationTSResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStationTS", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStationTS")
    @ResponseWrapper(localName = "GetHBGuestStationTSResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStationTSResponse")
    public ArrayOfStationTS getHBGuestStationTS(
        @WebParam(name = "measNum", targetNamespace = "http://www.dwr.state.co.us/")
        int measNum,
        @WebParam(name = "startDate", targetNamespace = "http://www.dwr.state.co.us/")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://www.dwr.state.co.us/")
        String endDate,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "WSDisclaimerHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "WSDisclaimerHeader")
        Holder<WSDisclaimerHeader> wsDisclaimerHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest structure records by water division (must be between 1 and 7).
     * 
     * @param hbStatusHeader
     * @param div
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStructure
     */
    @WebMethod(operationName = "GetHBGuestStructureByDIV", action = "http://www.dwr.state.co.us/GetHBGuestStructureByDIV")
    @WebResult(name = "GetHBGuestStructureByDIVResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStructureByDIV", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureByDIV")
    @ResponseWrapper(localName = "GetHBGuestStructureByDIVResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureByDIVResponse")
    public ArrayOfStructure getHBGuestStructureByDIV(
        @WebParam(name = "div", targetNamespace = "http://www.dwr.state.co.us/")
        int div,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest structure records by water district (must be between 1 and 80).
     * 
     * @param hbStatusHeader
     * @param wd
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStructure
     */
    @WebMethod(operationName = "GetHBGuestStructureByWD", action = "http://www.dwr.state.co.us/GetHBGuestStructureByWD")
    @WebResult(name = "GetHBGuestStructureByWDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStructureByWD", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureByWD")
    @ResponseWrapper(localName = "GetHBGuestStructureByWDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureByWDResponse")
    public ArrayOfStructure getHBGuestStructureByWD(
        @WebParam(name = "wd", targetNamespace = "http://www.dwr.state.co.us/")
        int wd,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest structure records by WDID.
     * 
     * @param hbStatusHeader
     * @param wdid
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStructure
     */
    @WebMethod(operationName = "GetHBGuestStructureByWDID", action = "http://www.dwr.state.co.us/GetHBGuestStructureByWDID")
    @WebResult(name = "GetHBGuestStructureByWDIDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStructureByWDID", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureByWDID")
    @ResponseWrapper(localName = "GetHBGuestStructureByWDIDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureByWDIDResponse")
    public ArrayOfStructure getHBGuestStructureByWDID(
        @WebParam(name = "WDID", targetNamespace = "http://www.dwr.state.co.us/")
        String wdid,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest StructureDailyTS records by WDID, start date, end date (mm/dd/yyyy).
     * 
     * @param hbStatusHeader
     * @param wdid
     * @param startDate
     * @param endDate
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStructureDailyTS
     */
    @WebMethod(operationName = "GetHBGuestStructureDailyTSByWDID", action = "http://www.dwr.state.co.us/GetHBGuestStructureDailyTSByWDID")
    @WebResult(name = "GetHBGuestStructureDailyTSByWDIDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStructureDailyTSByWDID", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureDailyTSByWDID")
    @ResponseWrapper(localName = "GetHBGuestStructureDailyTSByWDIDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureDailyTSByWDIDResponse")
    public ArrayOfStructureDailyTS getHBGuestStructureDailyTSByWDID(
        @WebParam(name = "wdid", targetNamespace = "http://www.dwr.state.co.us/")
        String wdid,
        @WebParam(name = "startDate", targetNamespace = "http://www.dwr.state.co.us/")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://www.dwr.state.co.us/")
        String endDate,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest StructureDailyTS records by Meas Number, start date, end date (mm/dd/yyyy).
     * 
     * @param hbStatusHeader
     * @param startDate
     * @param measNum
     * @param endDate
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStructureDailyTS
     */
    @WebMethod(operationName = "GetHBGuestStructureDailyTSByMeasNum", action = "http://www.dwr.state.co.us/GetHBGuestStructureDailyTSByMeasNum")
    @WebResult(name = "GetHBGuestStructureDailyTSByMeasNumResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStructureDailyTSByMeasNum", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureDailyTSByMeasNum")
    @ResponseWrapper(localName = "GetHBGuestStructureDailyTSByMeasNumResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureDailyTSByMeasNumResponse")
    public ArrayOfStructureDailyTS getHBGuestStructureDailyTSByMeasNum(
        @WebParam(name = "measNum", targetNamespace = "http://www.dwr.state.co.us/")
        int measNum,
        @WebParam(name = "startDate", targetNamespace = "http://www.dwr.state.co.us/")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://www.dwr.state.co.us/")
        String endDate,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest StructureDailyTS records by WDID, start year and end year (4 digits: YYYY).
     * 
     * @param hbStatusHeader
     * @param wdid
     * @param endYear
     * @param startYear
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStructureMonthlyTS
     */
    @WebMethod(operationName = "GetHBGuestStructureMonthlyTSByWDID", action = "http://www.dwr.state.co.us/GetHBGuestStructureMonthlyTSByWDID")
    @WebResult(name = "GetHBGuestStructureMonthlyTSByWDIDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStructureMonthlyTSByWDID", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureMonthlyTSByWDID")
    @ResponseWrapper(localName = "GetHBGuestStructureMonthlyTSByWDIDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureMonthlyTSByWDIDResponse")
    public ArrayOfStructureMonthlyTS getHBGuestStructureMonthlyTSByWDID(
        @WebParam(name = "wdid", targetNamespace = "http://www.dwr.state.co.us/")
        String wdid,
        @WebParam(name = "startYear", targetNamespace = "http://www.dwr.state.co.us/")
        short startYear,
        @WebParam(name = "endYear", targetNamespace = "http://www.dwr.state.co.us/")
        short endYear,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest StructureDailyTS records by Meas Number, start year and end year (4 digits: YYYY).
     * 
     * @param hbStatusHeader
     * @param endYear
     * @param measNum
     * @param startYear
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStructureMonthlyTS
     */
    @WebMethod(operationName = "GetHBGuestStructureMonthlyTSByMeasNum", action = "http://www.dwr.state.co.us/GetHBGuestStructureMonthlyTSByMeasNum")
    @WebResult(name = "GetHBGuestStructureMonthlyTSByMeasNumResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStructureMonthlyTSByMeasNum", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureMonthlyTSByMeasNum")
    @ResponseWrapper(localName = "GetHBGuestStructureMonthlyTSByMeasNumResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureMonthlyTSByMeasNumResponse")
    public ArrayOfStructureMonthlyTS getHBGuestStructureMonthlyTSByMeasNum(
        @WebParam(name = "measNum", targetNamespace = "http://www.dwr.state.co.us/")
        int measNum,
        @WebParam(name = "startYear", targetNamespace = "http://www.dwr.state.co.us/")
        short startYear,
        @WebParam(name = "endYear", targetNamespace = "http://www.dwr.state.co.us/")
        short endYear,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest StructureAnnuallyTS records by WDID, start year and end year (4 digits : YYYY).
     * 
     * @param hbStatusHeader
     * @param wdid
     * @param endYear
     * @param startYear
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStructureAnnuallyTS
     */
    @WebMethod(operationName = "GetHBGuestStructureAnnuallyTSByWDID", action = "http://www.dwr.state.co.us/GetHBGuestStructureAnnuallyTSByWDID")
    @WebResult(name = "GetHBGuestStructureAnnuallyTSByWDIDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStructureAnnuallyTSByWDID", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureAnnuallyTSByWDID")
    @ResponseWrapper(localName = "GetHBGuestStructureAnnuallyTSByWDIDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureAnnuallyTSByWDIDResponse")
    public ArrayOfStructureAnnuallyTS getHBGuestStructureAnnuallyTSByWDID(
        @WebParam(name = "wdid", targetNamespace = "http://www.dwr.state.co.us/")
        String wdid,
        @WebParam(name = "startYear", targetNamespace = "http://www.dwr.state.co.us/")
        short startYear,
        @WebParam(name = "endYear", targetNamespace = "http://www.dwr.state.co.us/")
        short endYear,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest StructureAnnuallyTS records by Meas Number, start year and end year (4 digits : YYYY).
     * 
     * @param hbStatusHeader
     * @param endYear
     * @param measNum
     * @param startYear
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStructureAnnuallyTS
     */
    @WebMethod(operationName = "GetHBGuestStructureAnnuallyTSByMeasNum", action = "http://www.dwr.state.co.us/GetHBGuestStructureAnnuallyTSByMeasNum")
    @WebResult(name = "GetHBGuestStructureAnnuallyTSByMeasNumResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStructureAnnuallyTSByMeasNum", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureAnnuallyTSByMeasNum")
    @ResponseWrapper(localName = "GetHBGuestStructureAnnuallyTSByMeasNumResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureAnnuallyTSByMeasNumResponse")
    public ArrayOfStructureAnnuallyTS getHBGuestStructureAnnuallyTSByMeasNum(
        @WebParam(name = "measNum", targetNamespace = "http://www.dwr.state.co.us/")
        int measNum,
        @WebParam(name = "startYear", targetNamespace = "http://www.dwr.state.co.us/")
        short startYear,
        @WebParam(name = "endYear", targetNamespace = "http://www.dwr.state.co.us/")
        short endYear,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest StructureDiversionComments records by WDID, start year and end year(4 digits: YYYY).
     * 
     * @param hbStatusHeader
     * @param wdid
     * @param endYear
     * @param startYear
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStructureDiversionComments
     */
    @WebMethod(operationName = "GetHBGuestStructureDiversionCommentsByWDID", action = "http://www.dwr.state.co.us/GetHBGuestStructureDiversionCommentsByWDID")
    @WebResult(name = "GetHBGuestStructureDiversionCommentsByWDIDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStructureDiversionCommentsByWDID", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureDiversionCommentsByWDID")
    @ResponseWrapper(localName = "GetHBGuestStructureDiversionCommentsByWDIDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureDiversionCommentsByWDIDResponse")
    public ArrayOfStructureDiversionComments getHBGuestStructureDiversionCommentsByWDID(
        @WebParam(name = "wdid", targetNamespace = "http://www.dwr.state.co.us/")
        String wdid,
        @WebParam(name = "startYear", targetNamespace = "http://www.dwr.state.co.us/")
        short startYear,
        @WebParam(name = "endYear", targetNamespace = "http://www.dwr.state.co.us/")
        short endYear,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest StructureDiversionComments records by meas number, start year and end year(4 digits: YYYY).
     * 
     * @param hbStatusHeader
     * @param endYear
     * @param measNum
     * @param startYear
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStructureDiversionComments
     */
    @WebMethod(operationName = "GetHBGuestStructureDiversionCommentsByMeasNumber", action = "http://www.dwr.state.co.us/GetHBGuestStructureDiversionCommentsByMeasNumber")
    @WebResult(name = "GetHBGuestStructureDiversionCommentsByMeasNumberResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStructureDiversionCommentsByMeasNumber", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureDiversionCommentsByMeasNumber")
    @ResponseWrapper(localName = "GetHBGuestStructureDiversionCommentsByMeasNumberResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureDiversionCommentsByMeasNumberResponse")
    public ArrayOfStructureDiversionComments getHBGuestStructureDiversionCommentsByMeasNumber(
        @WebParam(name = "measNum", targetNamespace = "http://www.dwr.state.co.us/")
        int measNum,
        @WebParam(name = "startYear", targetNamespace = "http://www.dwr.state.co.us/")
        short startYear,
        @WebParam(name = "endYear", targetNamespace = "http://www.dwr.state.co.us/")
        short endYear,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest StructureIrrigSummaryTS records by WDID, start year and end year (4 digits: YYYY).
     * 
     * @param hbStatusHeader
     * @param wdid
     * @param endYear
     * @param startYear
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStructureIrrigSummaryTS
     */
    @WebMethod(operationName = "GetHBGuestStructureIrrigSummaryTS", action = "http://www.dwr.state.co.us/GetHBGuestStructureIrrigSummaryTS")
    @WebResult(name = "GetHBGuestStructureIrrigSummaryTSResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStructureIrrigSummaryTS", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureIrrigSummaryTS")
    @ResponseWrapper(localName = "GetHBGuestStructureIrrigSummaryTSResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureIrrigSummaryTSResponse")
    public ArrayOfStructureIrrigSummaryTS getHBGuestStructureIrrigSummaryTS(
        @WebParam(name = "wdid", targetNamespace = "http://www.dwr.state.co.us/")
        String wdid,
        @WebParam(name = "startYear", targetNamespace = "http://www.dwr.state.co.us/")
        short startYear,
        @WebParam(name = "endYear", targetNamespace = "http://www.dwr.state.co.us/")
        short endYear,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest StructureMeasType records by WDID.
     * 
     * @param hbStatusHeader
     * @param wdid
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStructureMeasType
     */
    @WebMethod(operationName = "GetHBGuestStructureMeasTypeByWDID", action = "http://www.dwr.state.co.us/GetHBGuestStructureMeasTypeByWDID")
    @WebResult(name = "GetHBGuestStructureMeasTypeByWDIDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStructureMeasTypeByWDID", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureMeasTypeByWDID")
    @ResponseWrapper(localName = "GetHBGuestStructureMeasTypeByWDIDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureMeasTypeByWDIDResponse")
    public ArrayOfStructureMeasType getHBGuestStructureMeasTypeByWDID(
        @WebParam(name = "wdid", targetNamespace = "http://www.dwr.state.co.us/")
        String wdid,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest StructureResMeas records by WDID, start year and end year (mm/dd/yyyy).
     * 
     * @param hbStatusHeader
     * @param wdid
     * @param startDate
     * @param endDate
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStructureResMeas
     */
    @WebMethod(operationName = "GetHBGuestStructureResMeas", action = "http://www.dwr.state.co.us/GetHBGuestStructureResMeas")
    @WebResult(name = "GetHBGuestStructureResMeasResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStructureResMeas", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureResMeas")
    @ResponseWrapper(localName = "GetHBGuestStructureResMeasResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureResMeasResponse")
    public ArrayOfStructureResMeas getHBGuestStructureResMeas(
        @WebParam(name = "wdid", targetNamespace = "http://www.dwr.state.co.us/")
        String wdid,
        @WebParam(name = "startDate", targetNamespace = "http://www.dwr.state.co.us/")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://www.dwr.state.co.us/")
        String endDate,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest StructureParcelUseTS records by WDID, start year and end year( 4 digits: YYYY).
     * 
     * @param hbStatusHeader
     * @param wdid
     * @param endYear
     * @param startYear
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfStructureParcelUseTS
     */
    @WebMethod(operationName = "GetHBGuestStructureParcelUseTS", action = "http://www.dwr.state.co.us/GetHBGuestStructureParcelUseTS")
    @WebResult(name = "GetHBGuestStructureParcelUseTSResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestStructureParcelUseTS", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureParcelUseTS")
    @ResponseWrapper(localName = "GetHBGuestStructureParcelUseTSResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestStructureParcelUseTSResponse")
    public ArrayOfStructureParcelUseTS getHBGuestStructureParcelUseTS(
        @WebParam(name = "wdid", targetNamespace = "http://www.dwr.state.co.us/")
        String wdid,
        @WebParam(name = "startYear", targetNamespace = "http://www.dwr.state.co.us/")
        short startYear,
        @WebParam(name = "endYear", targetNamespace = "http://www.dwr.state.co.us/")
        short endYear,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest Transact records by water district (must be between 1 and 80).
     * 
     * @param hbStatusHeader
     * @param wd
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfTransact
     */
    @WebMethod(operationName = "GetHBGuestTransactByWD", action = "http://www.dwr.state.co.us/GetHBGuestTransactByWD")
    @WebResult(name = "GetHBGuestTransactByWDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestTransactByWD", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestTransactByWD")
    @ResponseWrapper(localName = "GetHBGuestTransactByWDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestTransactByWDResponse")
    public ArrayOfTransact getHBGuestTransactByWD(
        @WebParam(name = "wd", targetNamespace = "http://www.dwr.state.co.us/")
        int wd,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest Transact records by WDID.
     * 
     * @param hbStatusHeader
     * @param wdid
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfTransact
     */
    @WebMethod(operationName = "GetHBGuestTransactByWDID", action = "http://www.dwr.state.co.us/GetHBGuestTransactByWDID")
    @WebResult(name = "GetHBGuestTransactByWDIDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestTransactByWDID", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestTransactByWDID")
    @ResponseWrapper(localName = "GetHBGuestTransactByWDIDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestTransactByWDIDResponse")
    public ArrayOfTransact getHBGuestTransactByWDID(
        @WebParam(name = "WDID", targetNamespace = "http://www.dwr.state.co.us/")
        String wdid,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest Transact records by water division (must be between 1 and 7).
     * 
     * @param hbStatusHeader
     * @param div
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfTransact
     */
    @WebMethod(operationName = "GetHBGuestTransactByDIV", action = "http://www.dwr.state.co.us/GetHBGuestTransactByDIV")
    @WebResult(name = "GetHBGuestTransactByDIVResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestTransactByDIV", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestTransactByDIV")
    @ResponseWrapper(localName = "GetHBGuestTransactByDIVResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestTransactByDIVResponse")
    public ArrayOfTransact getHBGuestTransactByDIV(
        @WebParam(name = "div", targetNamespace = "http://www.dwr.state.co.us/")
        int div,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest Water Division records.
     * 
     * @param hbStatusHeader
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfWaterDivision
     */
    @WebMethod(operationName = "GetHBGuestWaterDivision", action = "http://www.dwr.state.co.us/GetHBGuestWaterDivision")
    @WebResult(name = "GetHBGuestWaterDivisionResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestWaterDivision", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestWaterDivision")
    @ResponseWrapper(localName = "GetHBGuestWaterDivisionResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestWaterDivisionResponse")
    public ArrayOfWaterDivision getHBGuestWaterDivision(
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest Water District records.
     * 
     * @param hbStatusHeader
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfWaterDistrict
     */
    @WebMethod(operationName = "GetHBGuestWaterDistrict", action = "http://www.dwr.state.co.us/GetHBGuestWaterDistrict")
    @WebResult(name = "GetHBGuestWaterDistrictResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestWaterDistrict", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestWaterDistrict")
    @ResponseWrapper(localName = "GetHBGuestWaterDistrictResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestWaterDistrictResponse")
    public ArrayOfWaterDistrict getHBGuestWaterDistrict(
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest Well Permits records by water district (must be between 1 and 80).
     * 
     * @param hbStatusHeader
     * @param wd
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfWellPermits
     */
    @WebMethod(operationName = "GetHBGuestWellPermitsByWD", action = "http://www.dwr.state.co.us/GetHBGuestWellPermitsByWD")
    @WebResult(name = "GetHBGuestWellPermitsByWDResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestWellPermitsByWD", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestWellPermitsByWD")
    @ResponseWrapper(localName = "GetHBGuestWellPermitsByWDResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestWellPermitsByWDResponse")
    public ArrayOfWellPermits getHBGuestWellPermitsByWD(
        @WebParam(name = "wd", targetNamespace = "http://www.dwr.state.co.us/")
        int wd,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest station records by county.
     * 
     * @param hbStatusHeader
     * @param county
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfWellPermits
     */
    @WebMethod(operationName = "GetHBGuestWellPermitsByCounty", action = "http://www.dwr.state.co.us/GetHBGuestWellPermitsByCounty")
    @WebResult(name = "GetHBGuestWellPermitsByCountyResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestWellPermitsByCounty", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestWellPermitsByCounty")
    @ResponseWrapper(localName = "GetHBGuestWellPermitsByCountyResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestWellPermitsByCountyResponse")
    public ArrayOfWellPermits getHBGuestWellPermitsByCounty(
        @WebParam(name = "county", targetNamespace = "http://www.dwr.state.co.us/")
        String county,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

    /**
     * Retrieve HBGuest Well Permits records by receipt number.
     * 
     * @param hbStatusHeader
     * @param receipt
     * @param hbAuthenticationHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfWellPermits
     */
    @WebMethod(operationName = "GetHBGuestWellPermitsByReceipt", action = "http://www.dwr.state.co.us/GetHBGuestWellPermitsByReceipt")
    @WebResult(name = "GetHBGuestWellPermitsByReceiptResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetHBGuestWellPermitsByReceipt", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestWellPermitsByReceipt")
    @ResponseWrapper(localName = "GetHBGuestWellPermitsByReceiptResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetHBGuestWellPermitsByReceiptResponse")
    public ArrayOfWellPermits getHBGuestWellPermitsByReceipt(
        @WebParam(name = "receipt", targetNamespace = "http://www.dwr.state.co.us/")
        String receipt,
        @WebParam(name = "HBAuthenticationHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, partName = "HBAuthenticationHeader")
        HBAuthenticationHeader hbAuthenticationHeader,
        @WebParam(name = "HbStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "HbStatusHeader")
        Holder<HbStatusHeader> hbStatusHeader);

}
